Assignment No 1

In [1]:
class BankAcc:
	def __init__(self,name,balance):
		self.name=name
		self.balance=balance

	def dis(self):
		print("\n**** Welcome ",self.name," *****")
		print("\nYour account is created with name:",self.name,"	 Current balance:",self.balance)

	def deposit(self):
		amount=int(input("\nEnter Amount to be deposited:"))
		Bal=self.balance+amount
		print("\n**** congratulations ",self.name," Your money is deposited *****")
		print("\ncurrent balance:",Bal)
		return Bal		

	def withdraw(self,Bal):
		amount=int(input("\nEnter Amount to be withdraw:"))
		print("\n**** congratulations ",self.name," Your money is withdraw *****")
		print("\nWithdraw Amount:",amount,"		current balance (before withdraw):",Bal)
		BA=Bal-amount;
		print("\n 		Current balance (after withdraw) :",BA)
		return BA



num=int(input("\n\nHow many Account you want to add:"))

for i in range(0,num):
	print("\n*********Enter Details of Account holder :",i+1,"******")

	name=input("\nEnter the name of Account holder:")
	balance=int(input("\nEnter current balance:"))

	B=BankAcc(name,balance)
	B.dis()

	B1=B.deposit()

	B.withdraw(B1)

How many Account you want to add:2

*********Enter Details of Account holder : 1 ******

Enter the name of Account holder:SNEHAL

Enter current balance:10000

**** Welcome  SNEHAL  *****

Your account is created with name: SNEHAL 	 Current balance: 10000

Enter Amount to be deposited:5000

**** congratulations  SNEHAL  Your money is deposited *****

current balance: 15000

Enter Amount to be withdraw:3000

**** congratulations  SNEHAL  Your money is withdraw *****

Withdraw Amount: 3000 		current balance (before withdraw): 15000

 		Current balance (after withdraw) : 12000

*********Enter Details of Account holder : 2 ******

Enter the name of Account holder:AARYA

Enter current balance:5000

**** Welcome  AARYA  *****

Your account is created with name: AARYA 	 Current balance: 5000

Enter Amount to be deposited:2000

**** congratulations  AARYA  Your money is deposited *****

current balance: 7000

Enter Amount to be withdraw:1000

**** congratulations  AARYA  Your money is withdraw *****

Withdraw Amount: 1000 		current balance (before withdraw): 7000

 		Current balance (after withdraw) : 6000

Assignment No 2

In [2]:
import math
class CONE:

	def __init__(self,radius,height):
		self.radius=radius
		self.height=height


	def display(self):
		print("Radius :",self.radius,"Height:",self.height)

	def calvolume(self):
		volume=math.pi*(self.radius*self.radius)*(self.height/3)
		print("\nVolume of cone is:",volume)

	def calarea(self):
		a=math.pi*self.radius
		b=self.radius+math.sqrt((self.height*self.height)+(self.radius*self.radius))
		area=a*b
		print("\nSurface area of cone is:",area)



C=CONE(2,4)
C.display()
C.calvolume()
C.calarea()

Radius : 2 Height: 4

Volume of cone is: 16.755160819145562

Surface area of cone is: 40.665629538522076